### ISSUE TITLE
Dependency on six.moves? 

### ISSUE THREAD

**Issue by orsenthil** [simonw/llm#436]
```
$ python3
Python 3.13.0a4+ (heads/main:bb66600558, Mar 12 2024, 14:06:50) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D
$ pip install llm
```

And when I use `llm` I am greeted with this exception.

```
Traceback (most recent call last):
  File "/Users/senthilx/cpython/virtualenvs/python313/bin/llm", line 5, in <module>
    from llm.cli import cli
  File "/Users/senthilx/cpython/virtualenvs/python313/lib/python3.13/site-packages/llm/__init__.py", line 16, in <module>
    from .embeddings import Collection
  File "/Users/senthilx/cpython/virtualenvs/python313/lib/python3.13/site-packages/llm/embeddings.py", line 7, in <module>
    from sqlite_utils import Database
  File "/Users/senthilx/cpython/virtualenvs/python313/lib/python3.13/site-packages/sqlite_utils/__init__.py", line 1, in <module>
    from .utils import suggest_column_types
  File "/Users/senthilx/cpython/virtualenvs/python313/lib/python3.13/site-packages/sqlite_utils/utils.py", line 11, in <module>
    from . import recipes
  File "/Users/senthilx/cpython/virtualenvs/python313/lib/python3.13/site-packages/sqlite_utils/recipes.py", line 1, in <module>
    from dateutil import parser
  File "/Users/senthilx/cpython/virtualenvs/python313/lib/python3.13/site-packages/dateutil/__init__.py", line 16, in __getattr__
    return importlib.import_module("." + name, __name__)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/senthilx/cpython/installs/python313/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/senthilx/cpython/virtualenvs/python313/lib/python3.13/site-packages/dateutil/parser/__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "/Users/senthilx/cpython/virtualenvs/python313/lib/python3.13/site-packages/dateutil/parser/_parser.py", line 50, in <module>
    from .. import tz
  File "/Users/senthilx/cpython/virtualenvs/python313/lib/python3.13/site-packages/dateutil/__init__.py", line 16, in __getattr__
    return importlib.import_module("." + name, __name__)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/senthilx/cpython/installs/python313/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/senthilx/cpython/virtualenvs/python313/lib/python3.13/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/Users/senthilx/cpython/virtualenvs/python313/lib/python3.13/site-packages/dateutil/tz/tz.py", line 21, in <module>
    from six.moves import _thread
ModuleNotFoundError: No module named 'six.moves'
```

**Comment by simonw** [comment]
Huh, weird - looks like I get that from the `dateutil` dependency.

Looks like it's not compatible with Python 3.13.

**Comment by simonw** [comment]
Relevant issue on `dateutil`:
- https://github.com/dateutil/dateutil/issues/1314

They landed a fix for that two weeks ago, I think in https://github.com/dateutil/dateutil/releases/tag/2.9.0

**Comment by simonw** [comment]
That dependency came in through `sqlite-utils` - and that library doesn't pin a version of `python-dateutil`: https://github.com/simonw/sqlite-utils/blob/17eb8184d2794dc4d05f096a45d1fbe0ad426055/setup.py#L31 - so it shouldn't be pulling in an older version that depends on `six.moves`.

I tried running the test suite against 3.13 here: https://github.com/simonw/llm/actions/runs/8256183289/job/22584327623 - but it failed on trying to install `numpy` with this error:

```
        File "/tmp/pip-install-kwm98dz4/numpy_38f6672539034e76a8a4b9a5a5c0d37e/vendored-meson/meson/mesonbuild/dependencies/cmake.py", line 618, in _call_cmake
          build_dir = self._setup_cmake_dir(cmake_file)
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
        File "/tmp/pip-install-kwm98dz4/numpy_38f6672539034e76a8a4b9a5a5c0d37e/vendored-meson/meson/mesonbuild/dependencies/cmake.py", line 589, in _setup_cmake_dir
          cmake_txt = importlib.resources.read_text('mesonbuild.dependencies.data', cmake_file, encoding = 'utf-8')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'importlib.resources' has no attribute 'read_text'
```
So LLM doesn't seem to work with Python 3.13 alpha yet, but in this case that's because of `numpy`.

**Comment by simonw** [comment]
... actually no, the most recent release of `python-dateutil` DOES still depend on `six.moves`.

I found this issue:
- https://github.com/dateutil/dateutil/issues/1258
 
But it doesn't take 3.13 into account yet. I'll open a new one there.

**Comment by simonw** [comment]
Opened this:
- https://github.com/dateutil/dateutil/issues/1352

**Comment by orsenthil** [comment]
It seems like the `six` module addes `six.moves` _dynamically_ here - https://github.com/benjaminp/six/blob/master/six.py#L337
And shouldn't have caused this issue, even from a dependency. I am unsure what is happening.

**Comment by simonw** [comment]
Odd, I can't replicate this issue myself using Python 3.13 alpha installed via `pyenv`:
```bash
pyenv install 3.13.0a3
```
Then create a new virtual environment with it:
```bash
~/.pyenv/versions/3.13.0a3/bin/python -m venv /tmp/3.13.0a3
```
And install `llm` into that environment:
```bash
/tmp/3.13.0a3/bin/pip install llm
```
That install worked for me. Runing `llm` doesn't complain about `six`.... but it DOES complain about something else!
```bash
/tmp/3.13.0a3/bin/llm 'say hi'
```
```
Traceback (most recent call last):
  File "/tmp/3.13.0a3/bin/llm", line 5, in <module>
    from llm.cli import cli
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/llm/__init__.py", line 18, in <module>
    from .plugins import pm
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/llm/plugins.py", line 37, in <module>
    mod = importlib.import_module(plugin)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/simon/.pyenv/versions/3.13.0a3/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/llm/default_plugins/openai_models.py", line 7, in <module>
    import openai
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/openai/__init__.py", line 8, in <module>
    from . import types
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/openai/types/__init__.py", line 5, in <module>
    from .image import Image as Image
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/openai/types/image.py", line 5, in <module>
    from .._models import BaseModel
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/openai/_models.py", line 408, in <module>
    class FinalRequestOptions(pydantic.BaseModel):
    ...<59 lines>...
            model_construct = construct
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/pydantic/_internal/_model_construction.py", line 178, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/pydantic/_internal/_model_construction.py", line 452, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/pydantic/_internal/_fields.py", line 214, in collect_model_fields
    field_info = FieldInfo.from_annotated_attribute(ann_type, default)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/pydantic/fields.py", line 372, in from_annotated_attribute
    if _typing_extra.is_annotated(annotation):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/pydantic/_internal/_typing_extra.py", line 103, in is_annotated
    return origin is not None and lenient_issubclass(origin, Annotated)
                                  ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/pydantic/_internal/_utils.py", line 76, in lenient_issubclass
    return isinstance(cls, type) and issubclass(cls, class_or_tuple)
                                     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.pyenv/versions/3.13.0a3/lib/python3.13/typing.py", line 486, in __subclasscheck__
    raise TypeError(f"{self} cannot be used with issubclass()")
TypeError: typing.Annotated cannot be used with issubclass()
```

**Comment by orsenthil** [comment]
Oh, you are running into a pydantic issue.

>  I can't replicate this issue myself using Python 3.13 alpha installed via pyenv

That's odd. I installed python3.13 using source. But python3.13 may not be a culprit here. I see instances of `ModuleNotFoundError: No module named 'six.moves'` all over internet without any good answer or reason for it.

**Comment by orsenthil** [comment]
This might be some race condition in pip (or pip package dependencies). In another issue when I ran into this, I removed six and installed six, and it worked fine.

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — I think this one can be closed as already shipped.

The original report was that `pip install llm` failed on a Python 3.13 alpha build because the `dateutil` dependency (transitively via `sqlite-utils`) imported `six.moves` from an incompatible build. Python 3.13 (and 3.14) are now first-class supported.

Evidence:
- [`pyproject.toml`](https://github.com/simonw/llm/blob/be27b91/pyproject.toml) — `requires-python = ">=3.10"` plus `Programming Language :: Python :: 3.13` and `:: 3.14` classifiers.
- [`.github/workflows/test.yml`](https://github.com/simonw/llm/blob/be27b91/.github/workflows/test.yml) — `python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]` in the test matrix, so every commit on `main` is verified against 3.13 and 3.14.
- [`.github/workflows/publish.yml`](https://github.com/simonw/llm/blob/be27b91/.github/workflows/publish.yml) — wheels published for the same 3.13/3.14 matrix.
- @simonw cross-filed the dateutil cause in [dateutil/dateutil#1352](https://github.com/dateutil/dateutil/issues/1352); the underlying `python-dateutil` issue has since been resolved upstream and the version that ships with current `sqlite-utils` no longer has the `six.moves` snag on 3.13.

If you're still hitting a 3.13-specific install failure on `main` (commit be27b91), happy to dig further with the traceback. Otherwise would you mind closing this out?

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually against current `main`.*
