### ISSUE TITLE
Error: Completions.create() got an unexpected keyword argument 'stream_options'

### ISSUE THREAD

**Issue by xezpeleta** [simonw/llm#605]
Hi!

After upgrading `llm` to 0.17.1, I get the following errors using OpenAI models:

```
$ llm -m gpt-4o-mini hi
Error: Completions.create() got an unexpected keyword argument 'stream_options'
```

The error disappear when I use the option  `--no-stream`:

```
$ llm -m gpt-4o-mini hi --no-stream
Hello! How can I assist you today?
```

## Solution

Upgrade OpenAI to the latest version:

```
pip install -U openai
```

**Comment by nipunsadvilkar** [comment]
@kevinburke There is solution in the main issue description.

See if it fixes it:
`pip install -U openai`
